import {
  AcademicCapIcon as AcademicCapIconOutline,
  AdjustmentsHorizontalIcon as AdjustmentsHorizontalIconOutline,
  AdjustmentsVerticalIcon as AdjustmentsVerticalIconOutline,
  ArchiveBoxArrowDownIcon as ArchiveBoxArrowDownIconOutline,
  ArchiveBoxXMarkIcon as ArchiveBoxXMarkIconOutline,
  ArchiveBoxIcon as ArchiveBoxIconOutline,
  ArrowDownCircleIcon as ArrowDownCircleIconOutline,
  ArrowDownLeftIcon as ArrowDownLeftIconOutline,
  ArrowDownOnSquareStackIcon as ArrowDownOnSquareStackIconOutline,
  ArrowDownOnSquareIcon as ArrowDownOnSquareIconOutline,
  ArrowDownRightIcon as ArrowDownRightIconOutline,
  ArrowDownTrayIcon as ArrowDownTrayIconOutline,
  ArrowDownIcon as ArrowDownIconOutline,
  ArrowLeftCircleIcon as ArrowLeftCircleIconOutline,
  ArrowLeftEndOnRectangleIcon as ArrowLeftEndOnRectangleIconOutline,
  ArrowLeftStartOnRectangleIcon as ArrowLeftStartOnRectangleIconOutline,
  ArrowLeftIcon as ArrowLeftIconOutline,
  ArrowLongDownIcon as ArrowLongDownIconOutline,
  ArrowLongLeftIcon as ArrowLongLeftIconOutline,
  ArrowLongRightIcon as ArrowLongRightIconOutline,
  ArrowLongUpIcon as ArrowLongUpIconOutline,
  ArrowPathRoundedSquareIcon as ArrowPathRoundedSquareIconOutline,
  ArrowPathIcon as ArrowPathIconOutline,
  ArrowRightCircleIcon as ArrowRightCircleIconOutline,
  ArrowRightEndOnRectangleIcon as ArrowRightEndOnRectangleIconOutline,
  ArrowRightStartOnRectangleIcon as ArrowRightStartOnRectangleIconOutline,
  ArrowRightIcon as ArrowRightIconOutline,
  ArrowTopRightOnSquareIcon as ArrowTopRightOnSquareIconOutline,
  ArrowTrendingDownIcon as ArrowTrendingDownIconOutline,
  ArrowTrendingUpIcon as ArrowTrendingUpIconOutline,
  ArrowUpCircleIcon as ArrowUpCircleIconOutline,
  ArrowUpLeftIcon as ArrowUpLeftIconOutline,
  ArrowUpOnSquareStackIcon as ArrowUpOnSquareStackIconOutline,
  ArrowUpOnSquareIcon as ArrowUpOnSquareIconOutline,
  ArrowUpRightIcon as ArrowUpRightIconOutline,
  ArrowUpTrayIcon as ArrowUpTrayIconOutline,
  ArrowUpIcon as ArrowUpIconOutline,
  ArrowUturnDownIcon as ArrowUturnDownIconOutline,
  ArrowUturnLeftIcon as ArrowUturnLeftIconOutline,
  ArrowUturnRightIcon as ArrowUturnRightIconOutline,
  ArrowUturnUpIcon as ArrowUturnUpIconOutline,
  ArrowsPointingInIcon as ArrowsPointingInIconOutline,
  ArrowsPointingOutIcon as ArrowsPointingOutIconOutline,
  ArrowsRightLeftIcon as ArrowsRightLeftIconOutline,
  ArrowsUpDownIcon as ArrowsUpDownIconOutline,
  AtSymbolIcon as AtSymbolIconOutline,
  BackspaceIcon as BackspaceIconOutline,
  BackwardIcon as BackwardIconOutline,
  BanknotesIcon as BanknotesIconOutline,
  Bars2Icon as Bars2IconOutline,
  Bars3BottomLeftIcon as Bars3BottomLeftIconOutline,
  Bars3BottomRightIcon as Bars3BottomRightIconOutline,
  Bars3CenterLeftIcon as Bars3CenterLeftIconOutline,
  Bars3Icon as Bars3IconOutline,
  Bars4Icon as Bars4IconOutline,
  BarsArrowDownIcon as BarsArrowDownIconOutline,
  BarsArrowUpIcon as BarsArrowUpIconOutline,
  Battery0Icon as Battery0IconOutline,
  Battery100Icon as Battery100IconOutline,
  Battery50Icon as Battery50IconOutline,
  BeakerIcon as BeakerIconOutline,
  BellAlertIcon as BellAlertIconOutline,
  BellSlashIcon as BellSlashIconOutline,
  BellSnoozeIcon as BellSnoozeIconOutline,
  BellIcon as BellIconOutline,
  BoltSlashIcon as BoltSlashIconOutline,
  BoltIcon as BoltIconOutline,
  BookOpenIcon as BookOpenIconOutline,
  BookmarkSlashIcon as BookmarkSlashIconOutline,
  BookmarkSquareIcon as BookmarkSquareIconOutline,
  BookmarkIcon as BookmarkIconOutline,
  BriefcaseIcon as BriefcaseIconOutline,
  BugAntIcon as BugAntIconOutline,
  BuildingLibraryIcon as BuildingLibraryIconOutline,
  BuildingOffice2Icon as BuildingOffice2IconOutline,
  BuildingOfficeIcon as BuildingOfficeIconOutline,
  BuildingStorefrontIcon as BuildingStorefrontIconOutline,
  CakeIcon as CakeIconOutline,
  CalculatorIcon as CalculatorIconOutline,
  CalendarDaysIcon as CalendarDaysIconOutline,
  CalendarIcon as CalendarIconOutline,
  CameraIcon as CameraIconOutline,
  ChartBarSquareIcon as ChartBarSquareIconOutline,
  ChartBarIcon as ChartBarIconOutline,
  ChartPieIcon as ChartPieIconOutline,
  ChatBubbleBottomCenterTextIcon as ChatBubbleBottomCenterTextIconOutline,
  ChatBubbleBottomCenterIcon as ChatBubbleBottomCenterIconOutline,
  ChatBubbleLeftEllipsisIcon as ChatBubbleLeftEllipsisIconOutline,
  ChatBubbleLeftRightIcon as ChatBubbleLeftRightIconOutline,
  ChatBubbleLeftIcon as ChatBubbleLeftIconOutline,
  ChatBubbleOvalLeftEllipsisIcon as ChatBubbleOvalLeftEllipsisIconOutline,
  ChatBubbleOvalLeftIcon as ChatBubbleOvalLeftIconOutline,
  CheckBadgeIcon as CheckBadgeIconOutline,
  CheckCircleIcon as CheckCircleIconOutline,
  CheckIcon as CheckIconOutline,
  ChevronDoubleDownIcon as ChevronDoubleDownIconOutline,
  ChevronDoubleLeftIcon as ChevronDoubleLeftIconOutline,
  ChevronDoubleRightIcon as ChevronDoubleRightIconOutline,
  ChevronDoubleUpIcon as ChevronDoubleUpIconOutline,
  ChevronDownIcon as ChevronDownIconOutline,
  ChevronLeftIcon as ChevronLeftIconOutline,
  ChevronRightIcon as ChevronRightIconOutline,
  ChevronUpDownIcon as ChevronUpDownIconOutline,
  ChevronUpIcon as ChevronUpIconOutline,
  CircleStackIcon as CircleStackIconOutline,
  ClipboardDocumentCheckIcon as ClipboardDocumentCheckIconOutline,
  ClipboardDocumentListIcon as ClipboardDocumentListIconOutline,
  ClipboardDocumentIcon as ClipboardDocumentIconOutline,
  ClipboardIcon as ClipboardIconOutline,
  ClockIcon as ClockIconOutline,
  CloudArrowDownIcon as CloudArrowDownIconOutline,
  CloudArrowUpIcon as CloudArrowUpIconOutline,
  CloudIcon as CloudIconOutline,
  CodeBracketSquareIcon as CodeBracketSquareIconOutline,
  CodeBracketIcon as CodeBracketIconOutline,
  Cog6ToothIcon as Cog6ToothIconOutline,
  Cog8ToothIcon as Cog8ToothIconOutline,
  CogIcon as CogIconOutline,
  CommandLineIcon as CommandLineIconOutline,
  ComputerDesktopIcon as ComputerDesktopIconOutline,
  CpuChipIcon as CpuChipIconOutline,
  CreditCardIcon as CreditCardIconOutline,
  CubeTransparentIcon as CubeTransparentIconOutline,
  CubeIcon as CubeIconOutline,
  CurrencyBangladeshiIcon as CurrencyBangladeshiIconOutline,
  CurrencyDollarIcon as CurrencyDollarIconOutline,
  CurrencyEuroIcon as CurrencyEuroIconOutline,
  CurrencyPoundIcon as CurrencyPoundIconOutline,
  CurrencyRupeeIcon as CurrencyRupeeIconOutline,
  CurrencyYenIcon as CurrencyYenIconOutline,
  CursorArrowRaysIcon as CursorArrowRaysIconOutline,
  CursorArrowRippleIcon as CursorArrowRippleIconOutline,
  DevicePhoneMobileIcon as DevicePhoneMobileIconOutline,
  DeviceTabletIcon as DeviceTabletIconOutline,
  DocumentArrowDownIcon as DocumentArrowDownIconOutline,
  DocumentArrowUpIcon as DocumentArrowUpIconOutline,
  DocumentChartBarIcon as DocumentChartBarIconOutline,
  DocumentCheckIcon as DocumentCheckIconOutline,
  DocumentDuplicateIcon as DocumentDuplicateIconOutline,
  DocumentMagnifyingGlassIcon as DocumentMagnifyingGlassIconOutline,
  DocumentMinusIcon as DocumentMinusIconOutline,
  DocumentPlusIcon as DocumentPlusIconOutline,
  DocumentTextIcon as DocumentTextIconOutline,
  DocumentIcon as DocumentIconOutline,
  EllipsisHorizontalCircleIcon as EllipsisHorizontalCircleIconOutline,
  EllipsisHorizontalIcon as EllipsisHorizontalIconOutline,
  EllipsisVerticalIcon as EllipsisVerticalIconOutline,
  EnvelopeOpenIcon as EnvelopeOpenIconOutline,
  EnvelopeIcon as EnvelopeIconOutline,
  ExclamationCircleIcon as ExclamationCircleIconOutline,
  ExclamationTriangleIcon as ExclamationTriangleIconOutline,
  EyeDropperIcon as EyeDropperIconOutline,
  EyeSlashIcon as EyeSlashIconOutline,
  EyeIcon as EyeIconOutline,
  FaceFrownIcon as FaceFrownIconOutline,
  FaceSmileIcon as FaceSmileIconOutline,
  FilmIcon as FilmIconOutline,
  FingerPrintIcon as FingerPrintIconOutline,
  FireIcon as FireIconOutline,
  FlagIcon as FlagIconOutline,
  FolderArrowDownIcon as FolderArrowDownIconOutline,
  FolderMinusIcon as FolderMinusIconOutline,
  FolderOpenIcon as FolderOpenIconOutline,
  FolderPlusIcon as FolderPlusIconOutline,
  FolderIcon as FolderIconOutline,
  ForwardIcon as ForwardIconOutline,
  FunnelIcon as FunnelIconOutline,
  GifIcon as GifIconOutline,
  GiftTopIcon as GiftTopIconOutline,
  GiftIcon as GiftIconOutline,
  GlobeAltIcon as GlobeAltIconOutline,
  GlobeAmericasIcon as GlobeAmericasIconOutline,
  GlobeAsiaAustraliaIcon as GlobeAsiaAustraliaIconOutline,
  GlobeEuropeAfricaIcon as GlobeEuropeAfricaIconOutline,
  HandRaisedIcon as HandRaisedIconOutline,
  HandThumbDownIcon as HandThumbDownIconOutline,
  HandThumbUpIcon as HandThumbUpIconOutline,
  HashtagIcon as HashtagIconOutline,
  HeartIcon as HeartIconOutline,
  HomeModernIcon as HomeModernIconOutline,
  HomeIcon as HomeIconOutline,
  IdentificationIcon as IdentificationIconOutline,
  InboxArrowDownIcon as InboxArrowDownIconOutline,
  InboxStackIcon as InboxStackIconOutline,
  InboxIcon as InboxIconOutline,
  InformationCircleIcon as InformationCircleIconOutline,
  KeyIcon as KeyIconOutline,
  LanguageIcon as LanguageIconOutline,
  LifebuoyIcon as LifebuoyIconOutline,
  LightBulbIcon as LightBulbIconOutline,
  LinkIcon as LinkIconOutline,
  ListBulletIcon as ListBulletIconOutline,
  LockClosedIcon as LockClosedIconOutline,
  LockOpenIcon as LockOpenIconOutline,
  MagnifyingGlassCircleIcon as MagnifyingGlassCircleIconOutline,
  MagnifyingGlassMinusIcon as MagnifyingGlassMinusIconOutline,
  MagnifyingGlassPlusIcon as MagnifyingGlassPlusIconOutline,
  MagnifyingGlassIcon as MagnifyingGlassIconOutline,
  MapPinIcon as MapPinIconOutline,
  MapIcon as MapIconOutline,
  MegaphoneIcon as MegaphoneIconOutline,
  MicrophoneIcon as MicrophoneIconOutline,
  MinusCircleIcon as MinusCircleIconOutline,
  MinusSmallIcon as MinusSmallIconOutline,
  MinusIcon as MinusIconOutline,
  MoonIcon as MoonIconOutline,
  MusicalNoteIcon as MusicalNoteIconOutline,
  NewspaperIcon as NewspaperIconOutline,
  NoSymbolIcon as NoSymbolIconOutline,
  PaintBrushIcon as PaintBrushIconOutline,
  PaperAirplaneIcon as PaperAirplaneIconOutline,
  PaperClipIcon as PaperClipIconOutline,
  PauseCircleIcon as PauseCircleIconOutline,
  PauseIcon as PauseIconOutline,
  PencilSquareIcon as PencilSquareIconOutline,
  PencilIcon as PencilIconOutline,
  PhoneArrowDownLeftIcon as PhoneArrowDownLeftIconOutline,
  PhoneArrowUpRightIcon as PhoneArrowUpRightIconOutline,
  PhoneXMarkIcon as PhoneXMarkIconOutline,
  PhoneIcon as PhoneIconOutline,
  PhotoIcon as PhotoIconOutline,
  PlayCircleIcon as PlayCircleIconOutline,
  PlayPauseIcon as PlayPauseIconOutline,
  PlayIcon as PlayIconOutline,
  PlusCircleIcon as PlusCircleIconOutline,
  PlusIcon as PlusIconOutline,
  PowerIcon as PowerIconOutline,
  PresentationChartBarIcon as PresentationChartBarIconOutline,
  PresentationChartLineIcon as PresentationChartLineIconOutline,
  PrinterIcon as PrinterIconOutline,
  PuzzlePieceIcon as PuzzlePieceIconOutline,
  QrCodeIcon as QrCodeIconOutline,
  QuestionMarkCircleIcon as QuestionMarkCircleIconOutline,
  QueueListIcon as QueueListIconOutline,
  RadioIcon as RadioIconOutline,
  ReceiptPercentIcon as ReceiptPercentIconOutline,
  ReceiptRefundIcon as ReceiptRefundIconOutline,
  RectangleGroupIcon as RectangleGroupIconOutline,
  RectangleStackIcon as RectangleStackIconOutline,
  RocketLaunchIcon as RocketLaunchIconOutline,
  RssIcon as RssIconOutline,
  ScaleIcon as ScaleIconOutline,
  ScissorsIcon as ScissorsIconOutline,
  ServerStackIcon as ServerStackIconOutline,
  ServerIcon as ServerIconOutline,
  ShareIcon as ShareIconOutline,
  ShieldCheckIcon as ShieldCheckIconOutline,
  ShieldExclamationIcon as ShieldExclamationIconOutline,
  ShoppingBagIcon as ShoppingBagIconOutline,
  ShoppingCartIcon as ShoppingCartIconOutline,
  SignalSlashIcon as SignalSlashIconOutline,
  SignalIcon as SignalIconOutline,
  SparklesIcon as SparklesIconOutline,
  SpeakerWaveIcon as SpeakerWaveIconOutline,
  SpeakerXMarkIcon as SpeakerXMarkIconOutline,
  Square2StackIcon as Square2StackIconOutline,
  Square3Stack3DIcon as Square3Stack3DIconOutline,
  Squares2X2Icon as Squares2X2IconOutline,
  SquaresPlusIcon as SquaresPlusIconOutline,
  StarIcon as StarIconOutline,
  StopCircleIcon as StopCircleIconOutline,
  StopIcon as StopIconOutline,
  SunIcon as SunIconOutline,
  SwatchIcon as SwatchIconOutline,
  TableCellsIcon as TableCellsIconOutline,
  TagIcon as TagIconOutline,
  TicketIcon as TicketIconOutline,
  TrashIcon as TrashIconOutline,
  TrophyIcon as TrophyIconOutline,
  TruckIcon as TruckIconOutline,
  TvIcon as TvIconOutline,
  UserCircleIcon as UserCircleIconOutline,
  UserGroupIcon as UserGroupIconOutline,
  UserMinusIcon as UserMinusIconOutline,
  UserPlusIcon as UserPlusIconOutline,
  UserIcon as UserIconOutline,
  UsersIcon as UsersIconOutline,
  VariableIcon as VariableIconOutline,
  VideoCameraSlashIcon as VideoCameraSlashIconOutline,
  VideoCameraIcon as VideoCameraIconOutline,
  ViewColumnsIcon as ViewColumnsIconOutline,
  ViewfinderCircleIcon as ViewfinderCircleIconOutline,
  WalletIcon as WalletIconOutline,
  WifiIcon as WifiIconOutline,
  WindowIcon as WindowIconOutline,
  WrenchScrewdriverIcon as WrenchScrewdriverIconOutline,
  WrenchIcon as WrenchIconOutline,
  XCircleIcon as XCircleIconOutline,
  XMarkIcon as XMarkIconOutline
} from '@heroicons/react/24/outline';

import {
  AcademicCapIcon as AcademicCapIconSolid,
  AdjustmentsHorizontalIcon as AdjustmentsHorizontalIconSolid,
  AdjustmentsVerticalIcon as AdjustmentsVerticalIconSolid,
  ArchiveBoxArrowDownIcon as ArchiveBoxArrowDownIconSolid,
  ArchiveBoxXMarkIcon as ArchiveBoxXMarkIconSolid,
  ArchiveBoxIcon as ArchiveBoxIconSolid,
  ArrowDownCircleIcon as ArrowDownCircleIconSolid,
  ArrowDownLeftIcon as ArrowDownLeftIconSolid,
  ArrowDownOnSquareStackIcon as ArrowDownOnSquareStackIconSolid,
  ArrowDownOnSquareIcon as ArrowDownOnSquareIconSolid,
  ArrowDownRightIcon as ArrowDownRightIconSolid,
  ArrowDownTrayIcon as ArrowDownTrayIconSolid,
  ArrowDownIcon as ArrowDownIconSolid,
  ArrowLeftCircleIcon as ArrowLeftCircleIconSolid,
  ArrowLeftEndOnRectangleIcon as ArrowLeftEndOnRectangleIconSolid,
  ArrowLeftStartOnRectangleIcon as ArrowLeftStartOnRectangleIconSolid,
  ArrowLeftIcon as ArrowLeftIconSolid,
  ArrowLongDownIcon as ArrowLongDownIconSolid,
  ArrowLongLeftIcon as ArrowLongLeftIconSolid,
  ArrowLongRightIcon as ArrowLongRightIconSolid,
  ArrowLongUpIcon as ArrowLongUpIconSolid,
  ArrowPathRoundedSquareIcon as ArrowPathRoundedSquareIconSolid,
  ArrowPathIcon as ArrowPathIconSolid,
  ArrowRightCircleIcon as ArrowRightCircleIconSolid,
  ArrowRightEndOnRectangleIcon as ArrowRightEndOnRectangleIconSolid,
  ArrowRightStartOnRectangleIcon as ArrowRightStartOnRectangleIconSolid,
  ArrowRightIcon as ArrowRightIconSolid,
  ArrowTopRightOnSquareIcon as ArrowTopRightOnSquareIconSolid,
  ArrowTrendingDownIcon as ArrowTrendingDownIconSolid,
  ArrowTrendingUpIcon as ArrowTrendingUpIconSolid,
  ArrowUpCircleIcon as ArrowUpCircleIconSolid,
  ArrowUpLeftIcon as ArrowUpLeftIconSolid,
  ArrowUpOnSquareStackIcon as ArrowUpOnSquareStackIconSolid,
  ArrowUpOnSquareIcon as ArrowUpOnSquareIconSolid,
  ArrowUpRightIcon as ArrowUpRightIconSolid,
  ArrowUpTrayIcon as ArrowUpTrayIconSolid,
  ArrowUpIcon as ArrowUpIconSolid,
  ArrowUturnDownIcon as ArrowUturnDownIconSolid,
  ArrowUturnLeftIcon as ArrowUturnLeftIconSolid,
  ArrowUturnRightIcon as ArrowUturnRightIconSolid,
  ArrowUturnUpIcon as ArrowUturnUpIconSolid,
  ArrowsPointingInIcon as ArrowsPointingInIconSolid,
  ArrowsPointingOutIcon as ArrowsPointingOutIconSolid,
  ArrowsRightLeftIcon as ArrowsRightLeftIconSolid,
  ArrowsUpDownIcon as ArrowsUpDownIconSolid,
  AtSymbolIcon as AtSymbolIconSolid,
  BackspaceIcon as BackspaceIconSolid,
  BackwardIcon as BackwardIconSolid,
  BanknotesIcon as BanknotesIconSolid,
  Bars2Icon as Bars2IconSolid,
  Bars3BottomLeftIcon as Bars3BottomLeftIconSolid,
  Bars3BottomRightIcon as Bars3BottomRightIconSolid,
  Bars3CenterLeftIcon as Bars3CenterLeftIconSolid,
  Bars3Icon as Bars3IconSolid,
  Bars4Icon as Bars4IconSolid,
  BarsArrowDownIcon as BarsArrowDownIconSolid,
  BarsArrowUpIcon as BarsArrowUpIconSolid,
  Battery0Icon as Battery0IconSolid,
  Battery100Icon as Battery100IconSolid,
  Battery50Icon as Battery50IconSolid,
  BeakerIcon as BeakerIconSolid,
  BellAlertIcon as BellAlertIconSolid,
  BellSlashIcon as BellSlashIconSolid,
  BellSnoozeIcon as BellSnoozeIconSolid,
  BellIcon as BellIconSolid,
  BoltSlashIcon as BoltSlashIconSolid,
  BoltIcon as BoltIconSolid,
  BookOpenIcon as BookOpenIconSolid,
  BookmarkSlashIcon as BookmarkSlashIconSolid,
  BookmarkSquareIcon as BookmarkSquareIconSolid,
  BookmarkIcon as BookmarkIconSolid,
  BriefcaseIcon as BriefcaseIconSolid,
  BugAntIcon as BugAntIconSolid,
  BuildingLibraryIcon as BuildingLibraryIconSolid,
  BuildingOffice2Icon as BuildingOffice2IconSolid,
  BuildingOfficeIcon as BuildingOfficeIconSolid,
  BuildingStorefrontIcon as BuildingStorefrontIconSolid,
  CakeIcon as CakeIconSolid,
  CalculatorIcon as CalculatorIconSolid,
  CalendarDaysIcon as CalendarDaysIconSolid,
  CalendarIcon as CalendarIconSolid,
  CameraIcon as CameraIconSolid,
  ChartBarSquareIcon as ChartBarSquareIconSolid,
  ChartBarIcon as ChartBarIconSolid,
  ChartPieIcon as ChartPieIconSolid,
  ChatBubbleBottomCenterTextIcon as ChatBubbleBottomCenterTextIconSolid,
  ChatBubbleBottomCenterIcon as ChatBubbleBottomCenterIconSolid,
  ChatBubbleLeftEllipsisIcon as ChatBubbleLeftEllipsisIconSolid,
  ChatBubbleLeftRightIcon as ChatBubbleLeftRightIconSolid,
  ChatBubbleLeftIcon as ChatBubbleLeftIconSolid,
  ChatBubbleOvalLeftEllipsisIcon as ChatBubbleOvalLeftEllipsisIconSolid,
  ChatBubbleOvalLeftIcon as ChatBubbleOvalLeftIconSolid,
  CheckBadgeIcon as CheckBadgeIconSolid,
  CheckCircleIcon as CheckCircleIconSolid,
  CheckIcon as CheckIconSolid,
  ChevronDoubleDownIcon as ChevronDoubleDownIconSolid,
  ChevronDoubleLeftIcon as ChevronDoubleLeftIconSolid,
  ChevronDoubleRightIcon as ChevronDoubleRightIconSolid,
  ChevronDoubleUpIcon as ChevronDoubleUpIconSolid,
  ChevronDownIcon as ChevronDownIconSolid,
  ChevronLeftIcon as ChevronLeftIconSolid,
  ChevronRightIcon as ChevronRightIconSolid,
  ChevronUpDownIcon as ChevronUpDownIconSolid,
  ChevronUpIcon as ChevronUpIconSolid,
  CircleStackIcon as CircleStackIconSolid,
  ClipboardDocumentCheckIcon as ClipboardDocumentCheckIconSolid,
  ClipboardDocumentListIcon as ClipboardDocumentListIconSolid,
  ClipboardDocumentIcon as ClipboardDocumentIconSolid,
  ClipboardIcon as ClipboardIconSolid,
  ClockIcon as ClockIconSolid,
  CloudArrowDownIcon as CloudArrowDownIconSolid,
  CloudArrowUpIcon as CloudArrowUpIconSolid,
  CloudIcon as CloudIconSolid,
  CodeBracketSquareIcon as CodeBracketSquareIconSolid,
  CodeBracketIcon as CodeBracketIconSolid,
  Cog6ToothIcon as Cog6ToothIconSolid,
  Cog8ToothIcon as Cog8ToothIconSolid,
  CogIcon as CogIconSolid,
  CommandLineIcon as CommandLineIconSolid,
  ComputerDesktopIcon as ComputerDesktopIconSolid,
  CpuChipIcon as CpuChipIconSolid,
  CreditCardIcon as CreditCardIconSolid,
  CubeTransparentIcon as CubeTransparentIconSolid,
  CubeIcon as CubeIconSolid,
  CurrencyBangladeshiIcon as CurrencyBangladeshiIconSolid,
  CurrencyDollarIcon as CurrencyDollarIconSolid,
  CurrencyEuroIcon as CurrencyEuroIconSolid,
  CurrencyPoundIcon as CurrencyPoundIconSolid,
  CurrencyRupeeIcon as CurrencyRupeeIconSolid,
  CurrencyYenIcon as CurrencyYenIconSolid,
  CursorArrowRaysIcon as CursorArrowRaysIconSolid,
  CursorArrowRippleIcon as CursorArrowRippleIconSolid,
  DevicePhoneMobileIcon as DevicePhoneMobileIconSolid,
  DeviceTabletIcon as DeviceTabletIconSolid,
  DocumentArrowDownIcon as DocumentArrowDownIconSolid,
  DocumentArrowUpIcon as DocumentArrowUpIconSolid,
  DocumentChartBarIcon as DocumentChartBarIconSolid,
  DocumentCheckIcon as DocumentCheckIconSolid,
  DocumentDuplicateIcon as DocumentDuplicateIconSolid,
  DocumentMagnifyingGlassIcon as DocumentMagnifyingGlassIconSolid,
  DocumentMinusIcon as DocumentMinusIconSolid,
  DocumentPlusIcon as DocumentPlusIconSolid,
  DocumentTextIcon as DocumentTextIconSolid,
  DocumentIcon as DocumentIconSolid,
  EllipsisHorizontalCircleIcon as EllipsisHorizontalCircleIconSolid,
  EllipsisHorizontalIcon as EllipsisHorizontalIconSolid,
  EllipsisVerticalIcon as EllipsisVerticalIconSolid,
  EnvelopeOpenIcon as EnvelopeOpenIconSolid,
  EnvelopeIcon as EnvelopeIconSolid,
  ExclamationCircleIcon as ExclamationCircleIconSolid,
  ExclamationTriangleIcon as ExclamationTriangleIconSolid,
  EyeDropperIcon as EyeDropperIconSolid,
  EyeSlashIcon as EyeSlashIconSolid,
  EyeIcon as EyeIconSolid,
  FaceFrownIcon as FaceFrownIconSolid,
  FaceSmileIcon as FaceSmileIconSolid,
  FilmIcon as FilmIconSolid,
  FingerPrintIcon as FingerPrintIconSolid,
  FireIcon as FireIconSolid,
  FlagIcon as FlagIconSolid,
  FolderArrowDownIcon as FolderArrowDownIconSolid,
  FolderMinusIcon as FolderMinusIconSolid,
  FolderOpenIcon as FolderOpenIconSolid,
  FolderPlusIcon as FolderPlusIconSolid,
  FolderIcon as FolderIconSolid,
  ForwardIcon as ForwardIconSolid,
  FunnelIcon as FunnelIconSolid,
  GifIcon as GifIconSolid,
  GiftTopIcon as GiftTopIconSolid,
  GiftIcon as GiftIconSolid,
  GlobeAltIcon as GlobeAltIconSolid,
  GlobeAmericasIcon as GlobeAmericasIconSolid,
  GlobeAsiaAustraliaIcon as GlobeAsiaAustraliaIconSolid,
  GlobeEuropeAfricaIcon as GlobeEuropeAfricaIconSolid,
  HandRaisedIcon as HandRaisedIconSolid,
  HandThumbDownIcon as HandThumbDownIconSolid,
  HandThumbUpIcon as HandThumbUpIconSolid,
  HashtagIcon as HashtagIconSolid,
  HeartIcon as HeartIconSolid,
  HomeModernIcon as HomeModernIconSolid,
  HomeIcon as HomeIconSolid,
  IdentificationIcon as IdentificationIconSolid,
  InboxArrowDownIcon as InboxArrowDownIconSolid,
  InboxStackIcon as InboxStackIconSolid,
  InboxIcon as InboxIconSolid,
  InformationCircleIcon as InformationCircleIconSolid,
  KeyIcon as KeyIconSolid,
  LanguageIcon as LanguageIconSolid,
  LifebuoyIcon as LifebuoyIconSolid,
  LightBulbIcon as LightBulbIconSolid,
  LinkIcon as LinkIconSolid,
  ListBulletIcon as ListBulletIconSolid,
  LockClosedIcon as LockClosedIconSolid,
  LockOpenIcon as LockOpenIconSolid,
  MagnifyingGlassCircleIcon as MagnifyingGlassCircleIconSolid,
  MagnifyingGlassMinusIcon as MagnifyingGlassMinusIconSolid,
  MagnifyingGlassPlusIcon as MagnifyingGlassPlusIconSolid,
  MagnifyingGlassIcon as MagnifyingGlassIconSolid,
  MapPinIcon as MapPinIconSolid,
  MapIcon as MapIconSolid,
  MegaphoneIcon as MegaphoneIconSolid,
  MicrophoneIcon as MicrophoneIconSolid,
  MinusCircleIcon as MinusCircleIconSolid,
  MinusIcon as MinusIconSolid,
  MoonIcon as MoonIconSolid,
  MusicalNoteIcon as MusicalNoteIconSolid,
  NewspaperIcon as NewspaperIconSolid,
  NoSymbolIcon as NoSymbolIconSolid,
  PaintBrushIcon as PaintBrushIconSolid,
  PaperAirplaneIcon as PaperAirplaneIconSolid,
  PaperClipIcon as PaperClipIconSolid,
  PauseCircleIcon as PauseCircleIconSolid,
  PauseIcon as PauseIconSolid,
  PencilSquareIcon as PencilSquareIconSolid,
  PencilIcon as PencilIconSolid,
  PhoneArrowDownLeftIcon as PhoneArrowDownLeftIconSolid,
  PhoneArrowUpRightIcon as PhoneArrowUpRightIconSolid,
  PhoneXMarkIcon as PhoneXMarkIconSolid,
  PhoneIcon as PhoneIconSolid,
  PhotoIcon as PhotoIconSolid,
  PlayCircleIcon as PlayCircleIconSolid,
  PlayPauseIcon as PlayPauseIconSolid,
  PlayIcon as PlayIconSolid,
  PlusCircleIcon as PlusCircleIconSolid,
  PlusIcon as PlusIconSolid,
  PowerIcon as PowerIconSolid,
  PresentationChartBarIcon as PresentationChartBarIconSolid,
  PresentationChartLineIcon as PresentationChartLineIconSolid,
  PrinterIcon as PrinterIconSolid,
  PuzzlePieceIcon as PuzzlePieceIconSolid,
  QrCodeIcon as QrCodeIconSolid,
  QuestionMarkCircleIcon as QuestionMarkCircleIconSolid,
  QueueListIcon as QueueListIconSolid,
  RadioIcon as RadioIconSolid,
  ReceiptPercentIcon as ReceiptPercentIconSolid,
  ReceiptRefundIcon as ReceiptRefundIconSolid,
  RectangleGroupIcon as RectangleGroupIconSolid,
  RectangleStackIcon as RectangleStackIconSolid,
  RocketLaunchIcon as RocketLaunchIconSolid,
  RssIcon as RssIconSolid,
  ScaleIcon as ScaleIconSolid,
  ScissorsIcon as ScissorsIconSolid,
  ServerStackIcon as ServerStackIconSolid,
  ServerIcon as ServerIconSolid,
  ShareIcon as ShareIconSolid,
  ShieldCheckIcon as ShieldCheckIconSolid,
  ShieldExclamationIcon as ShieldExclamationIconSolid,
  ShoppingBagIcon as ShoppingBagIconSolid,
  ShoppingCartIcon as ShoppingCartIconSolid,
  SignalSlashIcon as SignalSlashIconSolid,
  SignalIcon as SignalIconSolid,
  SparklesIcon as SparklesIconSolid,
  SpeakerWaveIcon as SpeakerWaveIconSolid,
  SpeakerXMarkIcon as SpeakerXMarkIconSolid,
  Square2StackIcon as Square2StackIconSolid,
  Square3Stack3DIcon as Square3Stack3DIconSolid,
  Squares2X2Icon as Squares2X2IconSolid,
  SquaresPlusIcon as SquaresPlusIconSolid,
  StarIcon as StarIconSolid,
  StopCircleIcon as StopCircleIconSolid,
  StopIcon as StopIconSolid,
  SunIcon as SunIconSolid,
  SwatchIcon as SwatchIconSolid,
  TableCellsIcon as TableCellsIconSolid,
  TagIcon as TagIconSolid,
  TicketIcon as TicketIconSolid,
  TrashIcon as TrashIconSolid,
  TrophyIcon as TrophyIconSolid,
  TruckIcon as TruckIconSolid,
  TvIcon as TvIconSolid,
  UserCircleIcon as UserCircleIconSolid,
  UserGroupIcon as UserGroupIconSolid,
  UserMinusIcon as UserMinusIconSolid,
  UserPlusIcon as UserPlusIconSolid,
  UserIcon as UserIconSolid,
  UsersIcon as UsersIconSolid,
  VariableIcon as VariableIconSolid,
  VideoCameraSlashIcon as VideoCameraSlashIconSolid,
  VideoCameraIcon as VideoCameraIconSolid,
  ViewColumnsIcon as ViewColumnsIconSolid,
  ViewfinderCircleIcon as ViewfinderCircleIconSolid,
  WalletIcon as WalletIconSolid,
  WifiIcon as WifiIconSolid,
  WindowIcon as WindowIconSolid,
  WrenchScrewdriverIcon as WrenchScrewdriverIconSolid,
  WrenchIcon as WrenchIconSolid,
  XCircleIcon as XCircleIconSolid,
  XMarkIcon as XMarkIconSolid
} from '@heroicons/react/24/solid';
import { AnimatedPlusSubtractIcon, SprintStackLogo } from './icons';

export const iconMapping = {
  SprintStackLogo,
  AnimatedPlusSubtractIcon,
  AcademicCapIconSolid,
  AdjustmentsHorizontalIconSolid,
  AdjustmentsVerticalIconSolid,
  ArchiveBoxArrowDownIconSolid,
  ArchiveBoxXMarkIconSolid,
  ArchiveBoxIconSolid,
  ArrowDownCircleIconSolid,
  ArrowDownLeftIconSolid,
  ArrowDownOnSquareStackIconSolid,
  ArrowDownOnSquareIconSolid,
  ArrowDownRightIconSolid,
  ArrowDownTrayIconSolid,
  ArrowDownIconSolid,
  ArrowLeftCircleIconSolid,
  ArrowLeftEndOnRectangleIconSolid,
  ArrowLeftStartOnRectangleIconSolid,
  ArrowLeftIconSolid,
  ArrowLongDownIconSolid,
  ArrowLongLeftIconSolid,
  ArrowLongRightIconSolid,
  ArrowLongUpIconSolid,
  ArrowPathRoundedSquareIconSolid,
  ArrowPathIconSolid,
  ArrowRightCircleIconSolid,
  ArrowRightEndOnRectangleIconSolid,
  ArrowRightStartOnRectangleIconSolid,
  ArrowRightIconSolid,
  ArrowTopRightOnSquareIconSolid,
  ArrowTrendingDownIconSolid,
  ArrowTrendingUpIconSolid,
  ArrowUpCircleIconSolid,
  ArrowUpLeftIconSolid,
  ArrowUpOnSquareStackIconSolid,
  ArrowUpOnSquareIconSolid,
  ArrowUpRightIconSolid,
  ArrowUpTrayIconSolid,
  ArrowUpIconSolid,
  ArrowUturnDownIconSolid,
  ArrowUturnLeftIconSolid,
  ArrowUturnRightIconSolid,
  ArrowUturnUpIconSolid,
  ArrowsPointingInIconSolid,
  ArrowsPointingOutIconSolid,
  ArrowsRightLeftIconSolid,
  ArrowsUpDownIconSolid,
  AtSymbolIconSolid,
  BackspaceIconSolid,
  BackwardIconSolid,
  BanknotesIconSolid,
  Bars2IconSolid,
  Bars3BottomLeftIconSolid,
  Bars3BottomRightIconSolid,
  Bars3CenterLeftIconSolid,
  Bars3IconSolid,
  Bars4IconSolid,
  BarsArrowDownIconSolid,
  BarsArrowUpIconSolid,
  Battery0IconSolid,
  Battery100IconSolid,
  Battery50IconSolid,
  BeakerIconSolid,
  BellAlertIconSolid,
  BellSlashIconSolid,
  BellSnoozeIconSolid,
  BellIconSolid,
  BoltSlashIconSolid,
  BoltIconSolid,
  BookOpenIconSolid,
  BookmarkSlashIconSolid,
  BookmarkSquareIconSolid,
  BookmarkIconSolid,
  BriefcaseIconSolid,
  BugAntIconSolid,
  BuildingLibraryIconSolid,
  BuildingOffice2IconSolid,
  BuildingOfficeIconSolid,
  BuildingStorefrontIconSolid,
  CakeIconSolid,
  CalculatorIconSolid,
  CalendarDaysIconSolid,
  CalendarIconSolid,
  CameraIconSolid,
  ChartBarSquareIconSolid,
  ChartBarIconSolid,
  ChartPieIconSolid,
  ChatBubbleBottomCenterTextIconSolid,
  ChatBubbleBottomCenterIconSolid,
  ChatBubbleLeftEllipsisIconSolid,
  ChatBubbleLeftRightIconSolid,
  ChatBubbleLeftIconSolid,
  ChatBubbleOvalLeftEllipsisIconSolid,
  ChatBubbleOvalLeftIconSolid,
  CheckBadgeIconSolid,
  CheckCircleIconSolid,
  CheckIconSolid,
  ChevronDoubleDownIconSolid,
  ChevronDoubleLeftIconSolid,
  ChevronDoubleRightIconSolid,
  ChevronDoubleUpIconSolid,
  ChevronDownIconSolid,
  ChevronLeftIconSolid,
  ChevronRightIconSolid,
  ChevronUpDownIconSolid,
  ChevronUpIconSolid,
  CircleStackIconSolid,
  ClipboardDocumentCheckIconSolid,
  ClipboardDocumentListIconSolid,
  ClipboardDocumentIconSolid,
  ClipboardIconSolid,
  ClockIconSolid,
  CloudArrowDownIconSolid,
  CloudArrowUpIconSolid,
  CloudIconSolid,
  CodeBracketSquareIconSolid,
  CodeBracketIconSolid,
  Cog6ToothIconSolid,
  Cog8ToothIconSolid,
  CogIconSolid,
  CommandLineIconSolid,
  ComputerDesktopIconSolid,
  CpuChipIconSolid,
  CreditCardIconSolid,
  CubeTransparentIconSolid,
  CubeIconSolid,
  CurrencyBangladeshiIconSolid,
  CurrencyDollarIconSolid,
  CurrencyEuroIconSolid,
  CurrencyPoundIconSolid,
  CurrencyRupeeIconSolid,
  CurrencyYenIconSolid,
  CursorArrowRaysIconSolid,
  CursorArrowRippleIconSolid,
  DevicePhoneMobileIconSolid,
  DeviceTabletIconSolid,
  DocumentArrowDownIconSolid,
  DocumentArrowUpIconSolid,
  DocumentChartBarIconSolid,
  DocumentCheckIconSolid,
  DocumentDuplicateIconSolid,
  DocumentMagnifyingGlassIconSolid,
  DocumentMinusIconSolid,
  DocumentPlusIconSolid,
  DocumentTextIconSolid,
  DocumentIconSolid,
  EllipsisHorizontalCircleIconSolid,
  EllipsisHorizontalIconSolid,
  EllipsisVerticalIconSolid,
  EnvelopeOpenIconSolid,
  EnvelopeIconSolid,
  ExclamationCircleIconSolid,
  ExclamationTriangleIconSolid,
  EyeDropperIconSolid,
  EyeSlashIconSolid,
  EyeIconSolid,
  FaceFrownIconSolid,
  FaceSmileIconSolid,
  FilmIconSolid,
  FingerPrintIconSolid,
  FireIconSolid,
  FlagIconSolid,
  FolderArrowDownIconSolid,
  FolderMinusIconSolid,
  FolderOpenIconSolid,
  FolderPlusIconSolid,
  FolderIconSolid,
  ForwardIconSolid,
  FunnelIconSolid,
  GifIconSolid,
  GiftTopIconSolid,
  GiftIconSolid,
  GlobeAltIconSolid,
  GlobeAmericasIconSolid,
  GlobeAsiaAustraliaIconSolid,
  GlobeEuropeAfricaIconSolid,
  HandRaisedIconSolid,
  HandThumbDownIconSolid,
  HandThumbUpIconSolid,
  HashtagIconSolid,
  HeartIconSolid,
  HomeModernIconSolid,
  HomeIconSolid,
  IdentificationIconSolid,
  InboxArrowDownIconSolid,
  InboxStackIconSolid,
  InboxIconSolid,
  InformationCircleIconSolid,
  KeyIconSolid,
  LanguageIconSolid,
  LifebuoyIconSolid,
  LightBulbIconSolid,
  LinkIconSolid,
  ListBulletIconSolid,
  LockClosedIconSolid,
  LockOpenIconSolid,
  MagnifyingGlassCircleIconSolid,
  MagnifyingGlassMinusIconSolid,
  MagnifyingGlassPlusIconSolid,
  MagnifyingGlassIconSolid,
  MapPinIconSolid,
  MapIconSolid,
  MegaphoneIconSolid,
  MicrophoneIconSolid,
  MinusCircleIconSolid,
  MinusIconSolid,
  MoonIconSolid,
  MusicalNoteIconSolid,
  NewspaperIconSolid,
  NoSymbolIconSolid,
  PaintBrushIconSolid,
  PaperAirplaneIconSolid,
  PaperClipIconSolid,
  PauseCircleIconSolid,
  PauseIconSolid,
  PencilSquareIconSolid,
  PencilIconSolid,
  PhoneArrowDownLeftIconSolid,
  PhoneArrowUpRightIconSolid,
  PhoneXMarkIconSolid,
  PhoneIconSolid,
  PhotoIconSolid,
  PlayCircleIconSolid,
  PlayPauseIconSolid,
  PlayIconSolid,
  PlusCircleIconSolid,
  PlusIconSolid,
  PowerIconSolid,
  PresentationChartBarIconSolid,
  PresentationChartLineIconSolid,
  PrinterIconSolid,
  PuzzlePieceIconSolid,
  QrCodeIconSolid,
  QuestionMarkCircleIconSolid,
  QueueListIconSolid,
  RadioIconSolid,
  ReceiptPercentIconSolid,
  ReceiptRefundIconSolid,
  RectangleGroupIconSolid,
  RectangleStackIconSolid,
  RocketLaunchIconSolid,
  RssIconSolid,
  ScaleIconSolid,
  ScissorsIconSolid,
  ServerStackIconSolid,
  ServerIconSolid,
  ShareIconSolid,
  ShieldCheckIconSolid,
  ShieldExclamationIconSolid,
  ShoppingBagIconSolid,
  ShoppingCartIconSolid,
  SignalSlashIconSolid,
  SignalIconSolid,
  SparklesIconSolid,
  SpeakerWaveIconSolid,
  SpeakerXMarkIconSolid,
  Square2StackIconSolid,
  Square3Stack3DIconSolid,
  Squares2X2IconSolid,
  SquaresPlusIconSolid,
  StarIconSolid,
  StopCircleIconSolid,
  StopIconSolid,
  SunIconSolid,
  SwatchIconSolid,
  TableCellsIconSolid,
  TagIconSolid,
  TicketIconSolid,
  TrashIconSolid,
  TrophyIconSolid,
  TruckIconSolid,
  TvIconSolid,
  UserCircleIconSolid,
  UserGroupIconSolid,
  UserMinusIconSolid,
  UserPlusIconSolid,
  UserIconSolid,
  UsersIconSolid,
  VariableIconSolid,
  VideoCameraSlashIconSolid,
  VideoCameraIconSolid,
  ViewColumnsIconSolid,
  ViewfinderCircleIconSolid,
  WalletIconSolid,
  WifiIconSolid,
  WindowIconSolid,
  WrenchScrewdriverIconSolid,
  WrenchIconSolid,
  XCircleIconSolid,
  XMarkIconSolid,
  AcademicCapIconOutline,
  AdjustmentsHorizontalIconOutline,
  AdjustmentsVerticalIconOutline,
  ArchiveBoxArrowDownIconOutline,
  ArchiveBoxXMarkIconOutline,
  ArchiveBoxIconOutline,
  ArrowDownCircleIconOutline,
  ArrowDownLeftIconOutline,
  ArrowDownOnSquareStackIconOutline,
  ArrowDownOnSquareIconOutline,
  ArrowDownRightIconOutline,
  ArrowDownTrayIconOutline,
  ArrowDownIconOutline,
  ArrowLeftCircleIconOutline,
  ArrowLeftEndOnRectangleIconOutline,
  ArrowLeftStartOnRectangleIconOutline,
  ArrowLeftIconOutline,
  ArrowLongDownIconOutline,
  ArrowLongLeftIconOutline,
  ArrowLongRightIconOutline,
  ArrowLongUpIconOutline,
  ArrowPathRoundedSquareIconOutline,
  ArrowPathIconOutline,
  ArrowRightCircleIconOutline,
  ArrowRightEndOnRectangleIconOutline,
  ArrowRightStartOnRectangleIconOutline,
  ArrowRightIconOutline,
  ArrowTopRightOnSquareIconOutline,
  ArrowTrendingDownIconOutline,
  ArrowTrendingUpIconOutline,
  ArrowUpCircleIconOutline,
  ArrowUpLeftIconOutline,
  ArrowUpOnSquareStackIconOutline,
  ArrowUpOnSquareIconOutline,
  ArrowUpRightIconOutline,
  ArrowUpTrayIconOutline,
  ArrowUpIconOutline,
  ArrowUturnDownIconOutline,
  ArrowUturnLeftIconOutline,
  ArrowUturnRightIconOutline,
  ArrowUturnUpIconOutline,
  ArrowsPointingInIconOutline,
  ArrowsPointingOutIconOutline,
  ArrowsRightLeftIconOutline,
  ArrowsUpDownIconOutline,
  AtSymbolIconOutline,
  BackspaceIconOutline,
  BackwardIconOutline,
  BanknotesIconOutline,
  Bars2IconOutline,
  Bars3BottomLeftIconOutline,
  Bars3BottomRightIconOutline,
  Bars3CenterLeftIconOutline,
  Bars3IconOutline,
  Bars4IconOutline,
  BarsArrowDownIconOutline,
  BarsArrowUpIconOutline,
  Battery0IconOutline,
  Battery100IconOutline,
  Battery50IconOutline,
  BeakerIconOutline,
  BellAlertIconOutline,
  BellSlashIconOutline,
  BellSnoozeIconOutline,
  BellIconOutline,
  BoltSlashIconOutline,
  BoltIconOutline,
  BookOpenIconOutline,
  BookmarkSlashIconOutline,
  BookmarkSquareIconOutline,
  BookmarkIconOutline,
  BriefcaseIconOutline,
  BugAntIconOutline,
  BuildingLibraryIconOutline,
  BuildingOffice2IconOutline,
  BuildingOfficeIconOutline,
  BuildingStorefrontIconOutline,
  CakeIconOutline,
  CalculatorIconOutline,
  CalendarDaysIconOutline,
  CalendarIconOutline,
  CameraIconOutline,
  ChartBarSquareIconOutline,
  ChartBarIconOutline,
  ChartPieIconOutline,
  ChatBubbleBottomCenterTextIconOutline,
  ChatBubbleBottomCenterIconOutline,
  ChatBubbleLeftEllipsisIconOutline,
  ChatBubbleLeftRightIconOutline,
  ChatBubbleLeftIconOutline,
  ChatBubbleOvalLeftEllipsisIconOutline,
  ChatBubbleOvalLeftIconOutline,
  CheckBadgeIconOutline,
  CheckCircleIconOutline,
  CheckIconOutline,
  ChevronDoubleDownIconOutline,
  ChevronDoubleLeftIconOutline,
  ChevronDoubleRightIconOutline,
  ChevronDoubleUpIconOutline,
  ChevronDownIconOutline,
  ChevronLeftIconOutline,
  ChevronRightIconOutline,
  ChevronUpDownIconOutline,
  ChevronUpIconOutline,
  CircleStackIconOutline,
  ClipboardDocumentCheckIconOutline,
  ClipboardDocumentListIconOutline,
  ClipboardDocumentIconOutline,
  ClipboardIconOutline,
  ClockIconOutline,
  CloudArrowDownIconOutline,
  CloudArrowUpIconOutline,
  CloudIconOutline,
  CodeBracketSquareIconOutline,
  CodeBracketIconOutline,
  Cog6ToothIconOutline,
  Cog8ToothIconOutline,
  CogIconOutline,
  CommandLineIconOutline,
  ComputerDesktopIconOutline,
  CpuChipIconOutline,
  CreditCardIconOutline,
  CubeTransparentIconOutline,
  CubeIconOutline,
  CurrencyBangladeshiIconOutline,
  CurrencyDollarIconOutline,
  CurrencyEuroIconOutline,
  CurrencyPoundIconOutline,
  CurrencyRupeeIconOutline,
  CurrencyYenIconOutline,
  CursorArrowRaysIconOutline,
  CursorArrowRippleIconOutline,
  DevicePhoneMobileIconOutline,
  DeviceTabletIconOutline,
  DocumentArrowDownIconOutline,
  DocumentArrowUpIconOutline,
  DocumentChartBarIconOutline,
  DocumentCheckIconOutline,
  DocumentDuplicateIconOutline,
  DocumentMagnifyingGlassIconOutline,
  DocumentMinusIconOutline,
  DocumentPlusIconOutline,
  DocumentTextIconOutline,
  DocumentIconOutline,
  EllipsisHorizontalCircleIconOutline,
  EllipsisHorizontalIconOutline,
  EllipsisVerticalIconOutline,
  EnvelopeOpenIconOutline,
  EnvelopeIconOutline,
  ExclamationCircleIconOutline,
  ExclamationTriangleIconOutline,
  EyeDropperIconOutline,
  EyeSlashIconOutline,
  EyeIconOutline,
  FaceFrownIconOutline,
  FaceSmileIconOutline,
  FilmIconOutline,
  FingerPrintIconOutline,
  FireIconOutline,
  FlagIconOutline,
  FolderArrowDownIconOutline,
  FolderMinusIconOutline,
  FolderOpenIconOutline,
  FolderPlusIconOutline,
  FolderIconOutline,
  ForwardIconOutline,
  FunnelIconOutline,
  GifIconOutline,
  GiftTopIconOutline,
  GiftIconOutline,
  GlobeAltIconOutline,
  GlobeAmericasIconOutline,
  GlobeAsiaAustraliaIconOutline,
  GlobeEuropeAfricaIconOutline,
  HandRaisedIconOutline,
  HandThumbDownIconOutline,
  HandThumbUpIconOutline,
  HashtagIconOutline,
  HeartIconOutline,
  HomeModernIconOutline,
  HomeIconOutline,
  IdentificationIconOutline,
  InboxArrowDownIconOutline,
  InboxStackIconOutline,
  InboxIconOutline,
  InformationCircleIconOutline,
  KeyIconOutline,
  LanguageIconOutline,
  LifebuoyIconOutline,
  LightBulbIconOutline,
  LinkIconOutline,
  ListBulletIconOutline,
  LockClosedIconOutline,
  LockOpenIconOutline,
  MagnifyingGlassCircleIconOutline,
  MagnifyingGlassMinusIconOutline,
  MagnifyingGlassPlusIconOutline,
  MagnifyingGlassIconOutline,
  MapPinIconOutline,
  MapIconOutline,
  MegaphoneIconOutline,
  MicrophoneIconOutline,
  MinusCircleIconOutline,
  MinusSmallIconOutline,
  MinusIconOutline,
  MoonIconOutline,
  MusicalNoteIconOutline,
  NewspaperIconOutline,
  NoSymbolIconOutline,
  PaintBrushIconOutline,
  PaperAirplaneIconOutline,
  PaperClipIconOutline,
  PauseCircleIconOutline,
  PauseIconOutline,
  PencilSquareIconOutline,
  PencilIconOutline,
  PhoneArrowDownLeftIconOutline,
  PhoneArrowUpRightIconOutline,
  PhoneXMarkIconOutline,
  PhoneIconOutline,
  PhotoIconOutline,
  PlayCircleIconOutline,
  PlayPauseIconOutline,
  PlayIconOutline,
  PlusCircleIconOutline,
  PlusIconOutline,
  PowerIconOutline,
  PresentationChartBarIconOutline,
  PresentationChartLineIconOutline,
  PrinterIconOutline,
  PuzzlePieceIconOutline,
  QrCodeIconOutline,
  QuestionMarkCircleIconOutline,
  QueueListIconOutline,
  RadioIconOutline,
  ReceiptPercentIconOutline,
  ReceiptRefundIconOutline,
  RectangleGroupIconOutline,
  RectangleStackIconOutline,
  RocketLaunchIconOutline,
  RssIconOutline,
  ScaleIconOutline,
  ScissorsIconOutline,
  ServerStackIconOutline,
  ServerIconOutline,
  ShareIconOutline,
  ShieldCheckIconOutline,
  ShieldExclamationIconOutline,
  ShoppingBagIconOutline,
  ShoppingCartIconOutline,
  SignalSlashIconOutline,
  SignalIconOutline,
  SparklesIconOutline,
  SpeakerWaveIconOutline,
  SpeakerXMarkIconOutline,
  Square2StackIconOutline,
  Square3Stack3DIconOutline,
  Squares2X2IconOutline,
  SquaresPlusIconOutline,
  StarIconOutline,
  StopCircleIconOutline,
  StopIconOutline,
  SunIconOutline,
  SwatchIconOutline,
  TableCellsIconOutline,
  TagIconOutline,
  TicketIconOutline,
  TrashIconOutline,
  TrophyIconOutline,
  TruckIconOutline,
  TvIconOutline,
  UserCircleIconOutline,
  UserGroupIconOutline,
  UserMinusIconOutline,
  UserPlusIconOutline,
  UserIconOutline,
  UsersIconOutline,
  VariableIconOutline,
  VideoCameraSlashIconOutline,
  VideoCameraIconOutline,
  ViewColumnsIconOutline,
  ViewfinderCircleIconOutline,
  WalletIconOutline,
  WifiIconOutline,
  WindowIconOutline,
  WrenchScrewdriverIconOutline,
  WrenchIconOutline,
  XCircleIconOutline,
  XMarkIconOutline
};
